baseURL = 'https://tilde.club/~bfj/'
languageCode = 'en-us'
title = 'Wallach IX'
copyright = "© Benjamin F Jones"
theme = 'archie'

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# never read the comments
# disqusShortname = "yourDisqusShortname"

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/benjaminfjones"

[[params.social]]
name = "Mastodon"
icon = "mastodon"
url = "@bfjvii@mathstodon.xyz"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
